services:
  postgres:
    image: postgres:16-alpine
    container_name: courselylabs-db
    environment:
      POSTGRES_DB: cursos_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
    ports:
      - "4321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d cursos_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
